import { useEffect, useState } from 'react';
import './StudentAttendanceReport.css';

const initial={from:'',to:'',course:'',batch:'',section:'',type:'',subject:'',comparison:'',percentage:''};
async function get(url){const response=await fetch(url,{headers:{Authorization:`Bearer ${localStorage.getItem('abit_session')}`}});const body=await response.json();if(!response.ok)throw new Error(body.message||'Unable to load report.');return body;}
export default function StudentAttendanceReport(){
  const [form,setForm]=useState(initial),[masters,setMasters]=useState(null),[rows,setRows]=useState(null),[loading,setLoading]=useState(true),[generating,setGenerating]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;get('/api/student-attendance').then(data=>{if(active)setMasters(data);}).catch(err=>{if(active)setError(err.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const change=(key,value)=>{setRows(null);setError('');setForm(current=>({...current,[key]:value,...(key==='course'?{batch:'',section:'',subject:''}:key==='batch'?{section:'',subject:''}:key==='type'?{subject:''}:{} )}));};
  const batches=(masters?.batches||[]).filter(x=>String(x.programme_id)===form.course);
  const sections=(masters?.sections||[]).filter(x=>batches.some(b=>String(b.id)===String(x.batch_id))&&(!form.batch||`${x.batch_id}:${x.semester_id}`===form.batch));
  const batchOptions=[...new Map((masters?.sections||[]).filter(x=>batches.some(b=>String(b.id)===String(x.batch_id))).map(x=>{const id=`${x.batch_id}:${x.semester_id}`;return [id,{id,name:`${batches.find(b=>String(b.id)===String(x.batch_id))?.name} [${masters.semesters.find(s=>String(s.id)===String(x.semester_id))?.name||'Semester'}]`}];})).values()];
  const subjects=(masters?.subjects||[]).filter(x=>!form.type||x.type===form.type);
  const select=(label,key,options,placeholder,required=false)=><label className={key==='course'?'sar-course':''}><span>{label}{required&&<b> *</b>}</span><select required={required} value={form[key]} onChange={e=>change(key,e.target.value)} disabled={loading||generating||(['batch','section'].includes(key)&&!form.course)}><option value="">{placeholder}</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
  const generate=async event=>{event.preventDefault();setError('');if(form.from&&form.to&&form.from>form.to){setError('From Date must be on or before To Date.');return;}setGenerating(true);setRows(null);try{const body=await get(`/api/student-attendance-report?${new URLSearchParams(form)}`);setRows(body.rows);}catch(err){setError(err.message);}finally{setGenerating(false);}};
  return <section className="student-report"><form onSubmit={generate}><div className="sar-dates"><label><span>From Date</span><input type="date" value={form.from} onChange={e=>change('from',e.target.value)}/></label><label><span>To Date</span><input type="date" value={form.to} onChange={e=>change('to',e.target.value)}/></label></div><div className="sar-filters">{select('Course','course',(masters?.programmes||[]).map(x=>({...x,name:x.code||x.name})),'Select Course',true)}{select('Batch','batch',batchOptions,'All Batches / Semesters')}{select('Section','section',sections,'All Sections')}{select('Subject Type','type',[...new Set((masters?.subjects||[]).map(x=>x.type))].filter(Boolean).map(x=>({id:x,name:`${x} Subjects`})),'All Subject Types')}{select('Subject Name','subject',subjects.map(x=>({...x,name:`${x.code}: ${x.name}`})),'--- Select Subject ---')}</div><div className="sar-percentage"><label><span>% Attendance Filtering</span><select value={form.comparison} onChange={e=>change('comparison',e.target.value)}><option value="">Select</option><option value="lt">Less than</option><option value="lte">Less than or equal to</option><option value="eq">Equal to</option><option value="gte">Greater than or equal to</option><option value="gt">Greater than</option></select></label><input aria-label="Attendance percentage" type="number" min="0" max="100" step="0.01" required={!!form.comparison} disabled={!form.comparison} value={form.percentage} onChange={e=>change('percentage',e.target.value)}/><button disabled={loading||generating||!masters}>{generating?'Generating…':'Generate'}</button></div></form>{loading&&<p role="status">Loading attendance filters…</p>}{error&&<p className="sar-error" role="alert">{error}</p>}{rows!==null&&<div className="sar-results"><h2>Student Attendance Report</h2><p>{rows.length} student{rows.length===1?'':'s'} found. Attendance is calculated from recorded student attendance for the selected classes.</p><div><table><thead><tr>{['Registration No.','Student','Classes','Present','Absent','Attendance %'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map(row=><tr key={row.id}><td>{row.registration_no}</td><td>{row.name}</td><td>{row.total}</td><td>{row.present}</td><td>{row.absent}</td><td>{row.percentage}%</td></tr>):<tr><td colSpan={6}>No attendance records match these filters.</td></tr>}</tbody></table></div></div>}</section>;
}
