import { useEffect, useState } from 'react';
import './SubjectWiseAttendanceReport.css';

const columns=[['programme_code','Course'],['batch_name','Batch'],['semester_name','Semester'],['section_name','Section'],['subject','Subject'],['faculty_name','Faculty']];
const value=(row,key)=>key==='subject'?`${row.subject_name} (${row.subject_code})`:row[key]||'';
async function get(url){
  const response=await fetch(url,{headers:{Authorization:`Bearer ${localStorage.getItem('abit_session')}`}});
  const body=await response.json();
  if(!response.ok)throw new Error(body.message||'Unable to load attendance report.');
  return body;
}
function Pager({page,setPage,total,size,setSize}){
  const pages=Math.max(1,Math.ceil(total/size));
  return <div className="swar-pagination"><label>Rows per page <select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select></label><span>Showing {total?(page-1)*size+1:0} to {Math.min(page*size,total)} of {total}</span><nav aria-label="Report pagination"><button disabled={page===1} onClick={()=>setPage(1)}>First</button><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button><button disabled={page===pages} onClick={()=>setPage(pages)}>Last</button></nav></div>;
}
export default function SubjectWiseAttendanceReport(){
  const [rows,setRows]=useState([]),[filters,setFilters]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [selected,setSelected]=useState(null),[detail,setDetail]=useState(null),[page,setPage]=useState(1),[size,setSize]=useState(10),[studentPage,setStudentPage]=useState(1),[studentSize,setStudentSize]=useState(10);
  useEffect(()=>{let active=true;get('/api/subject-wise-attendance-report').then(body=>{if(active)setRows(body.rows);}).catch(err=>{if(active)setError(err.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const visible=rows.filter(row=>columns.every(([key])=>!filters[key]||(key==='semester_name'?value(row,key).toLowerCase().includes(filters[key].toLowerCase()):value(row,key)===filters[key])));
  async function view(row){setSelected(row);setDetail(null);setStudentPage(1);setLoading(true);setError('');try{setDetail(await get(`/api/subject-wise-attendance-report/${row.id}`));}catch(err){setError(err.message);}finally{setLoading(false);}}
  const dateHeader=session=>{const date=new Date(`${session.date}T00:00:00`);return <><span className="swar-day">{String(date.getDate()).padStart(2,'0')}</span><strong>{date.toLocaleDateString('en-GB',{month:'long'})} {date.getFullYear()}</strong><small>{date.toLocaleDateString('en-GB',{weekday:'long'})}</small><small>{session.startTime?.slice(0,5)}–{session.endTime?.slice(0,5)}</small></>;};
  return <section className="subject-wise-report" aria-label="Subject-wise Attendance Report">
    {selected&&<header><div><h2>{value(selected,'subject')}</h2><p>{selected.programme_code} · {selected.batch_name} · {selected.semester_name} · {selected.section_name} · {selected.faculty_name}</p></div><button disabled={loading} onClick={()=>{setSelected(null);setDetail(null);setError('');}}>Back to Report</button></header>}
    {error&&<p role="alert" className="swar-error">{error}</p>}
    {selected?<>{loading?<p role="status">Loading student attendance…</p>:detail&&<><div className="swar-scroll"><table className="swar-detail"><thead><tr><th>Registration No.</th><th>Student Name</th>{detail.sessions.map(session=><th className="swar-date" key={session.id}>{dateHeader(session)}</th>)}<th>Summary</th><th>%</th></tr></thead><tbody>{detail.students.length?detail.students.slice((studentPage-1)*studentSize,studentPage*studentSize).map(student=><tr key={student.id}><td>{student.registration_no}</td><td>{student.name}</td>{detail.sessions.map(session=>{const status=student.attendance[session.id];return <td key={session.id} className={status==='PRESENT'?'swar-present':status==='ABSENT'?'swar-absent':''} title={status||'Not recorded'}>{status==='PRESENT'?'P':status==='ABSENT'?'A':'—'}</td>;})}<td>{student.present}/{student.total}</td><td><b>{student.percentage}%</b></td></tr>):<tr><td colSpan={detail.sessions.length+4}>No recorded student attendance for this subject allocation.</td></tr>}</tbody></table></div><p className="swar-legend">P = Present · A = Absent · — = Not recorded. Summary and percentage use recorded classes only.</p><Pager page={studentPage} setPage={setStudentPage} total={detail.students.length} size={studentSize} setSize={setStudentSize}/></>}</>:<><div className="swar-scroll"><table className="swar-list"><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}<th>View</th></tr><tr>{columns.map(([key,label])=><th key={key}>{key==='semester_name'?<input aria-label={`Filter ${label}`} value={filters[key]||''} onChange={e=>{setFilters({...filters,[key]:e.target.value});setPage(1);}}/>:<select aria-label={`Filter ${label}`} value={filters[key]||''} onChange={e=>{setFilters({...filters,[key]:e.target.value});setPage(1);}}><option value=""/>{[...new Set(rows.map(row=>value(row,key)))].filter(Boolean).sort().map(name=><option key={name}>{name}</option>)}</select>}</th>)}<th/></tr></thead><tbody>{loading?<tr><td colSpan="7" role="status">Loading Subject-wise Attendance Report…</td></tr>:visible.length?visible.slice((page-1)*size,page*size).map(row=><tr key={row.id}>{columns.map(([key])=><td key={key}>{value(row,key)}</td>)}<td><button className="swar-view" title="View student attendance" aria-label={`View attendance for ${value(row,'subject')}, ${row.batch_name}, ${row.section_name}, ${row.faculty_name}`} onClick={()=>view(row)}><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg></button></td></tr>):<tr><td colSpan="7">{error?'Report could not be loaded.':'No subjects match the selected filters.'}</td></tr>}</tbody></table></div>{!loading&&<Pager page={page} setPage={setPage} total={visible.length} size={size} setSize={setSize}/>}</>}
  </section>;
}
