import { useEffect, useState } from 'react';
import './SuperAdminPassword.css';

export default function SuperAdminPassword(){
  const [user,setUser]=useState(null),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let active=true;fetch('/api/auth/me',{headers:{Authorization:`Bearer ${localStorage.getItem('abit_session')}`}}).then(async response=>{if(!response.ok)return;const body=await response.json();if(active)setUser(body.user);}).catch(()=>{});return()=>{active=false;};},[]);
  if(!['SUPER_ADMIN','ADMIN','INSTITUTE_ADMIN'].includes(user?.role))return null;
  const generate=()=>{const bytes=crypto.getRandomValues(new Uint8Array(24));const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';setPassword(Array.from(bytes,value=>alphabet[value&63]).join(''));setMessage('Password generated. Save Password applies it to your account.');setError('');};
  const copy=async()=>{try{await navigator.clipboard.writeText(password);setMessage('Password copied.');setError('');}catch{setError('Unable to copy automatically. Use Show and copy the password manually.');}};
  const save=async event=>{event.preventDefault();setSaving(true);setError('');setMessage('');try{const response=await fetch('/api/auth/change-password',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${localStorage.getItem('abit_session')}`},body:JSON.stringify({newPassword:password})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message||'Unable to save password.');setMessage('Password saved successfully. Use this password the next time you sign in.');setPassword('');setVisible(false);}catch(err){setError(err.message);}finally{setSaving(false);}};
  return <section className="super-admin-password"><h3>{user.role==='SUPER_ADMIN'?'Super Admin Password':'Administrator Password'}</h3><p>Generate a password for <strong>{user.username}</strong>. Copy it before saving.</p><form onSubmit={save}><label>New Password<input type={visible?'text':'password'} autoComplete="new-password" minLength={8} required value={password} disabled={saving} onChange={e=>{setPassword(e.target.value);setMessage('');}}/></label><div><button type="button" onClick={generate} disabled={saving}>Generate Password</button><button type="button" onClick={()=>setVisible(value=>!value)} disabled={!password||saving}>{visible?'Hide':'Show'}</button><button type="button" onClick={copy} disabled={!password||saving}>Copy</button><button type="submit" className="primary" disabled={password.length<8||saving}>{saving?'Saving…':'Save Password'}</button></div></form>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="super-password-error">{error}</p>}</section>;
}
